### ISSUE TITLE
QA Checklist

### ISSUE THREAD

**Issue by timrwood** [timrwood/roost#3]
#### Roost

- [ ] Can be crafted
- [ ] Has localized name
- [ ] Textures look correct
- [ ] All modded chicken textures look correct
- [ ] Can insert a chicken with right click
- [ ] Can remove a chicken with shift+right click
- [ ] Does not replace vanilla chicken with modded chicken on right click
- [ ] Does not replace modded chicken with other modded chicken type on right click
- [ ] Does not replace modded chicken with same modded chicken with other stats on right click
- [ ] When roost has 15 chickens, right clicking with 1 of same chicken will add to stack correct amount
- [ ] When roost has 15 chickens, right clicking with 2 of same chicken will decrement held stack to 1
- [ ] When roost has 16 chickens, right clicking with 1 of same chicken will open GUI
- [ ] Vanilla drops feathers and eggs
- [ ] Modded drops correct item
- [ ] Drop progress does not reset when reloading world
- [ ] Hoppers can put chickens in
- [ ] Hoppers can not put anything in drop slots
- [ ] Hoppers pull drops out
- [ ] Hoppers do not pull chicken out
- [ ] [GUI] Shows drop progress on hover
- [ ] [GUI] Middle click fills chicken slot
- [ ] [GUI] Middle click does not put anything else in chicken slot
- [ ] [GUI] Middle click does not put anything in output slots
- [ ] [HWYLA] Shows vanilla chicken type
- [ ] [HWYLA] Shows modded chicken type with stats
- [ ] [HWYLA] Shows drop progress
- [ ] [HWYLA] Empty roost shows no progress

#### Breeder

- [ ] Can be crafted
- [ ] Has localized name
- [ ] Textures look correct
- [ ] Privacy textures look correct
- [ ] 2 vanilla chickens create a vanilla chicken
- [ ] 1 vanilla + 1 modded create both vanilla chickens and cloned modded chickens
- [ ] 2 modded of same type create improved chicken of same type
- [ ] 2 modded of different types create type a, type b, and cross breed type
- [ ] Breeding uses 2 seeds
- [ ] Breeding progress does not continue when there are not enough seeds
- [ ] Breeding progress does not reset when reloading world
- [ ] Hoppers can put seeds in
- [ ] Hoppers can put chickens in
- [ ] Hoppers can not put anything in drop slots
- [ ] Hoppers pull child chickens out
- [ ] Hoppers do not pull parent chickens out
- [ ] [GUI] Shows drop progress on hover
- [ ] [GUI] Middle click fills chicken slots
- [ ] [GUI] Middle click does not put anything else in chicken slots
- [ ] [GUI] Middle click does not put anything in output slots
- [ ] [HWYLA] Shows vanilla chicken types
- [ ] [HWYLA] Shows modded chicken types with stats
- [ ] [HWYLA] Shows drop progress
- [ ] [HWYLA] Show when there are no seeds
- [ ] [HWYLA] Empty breeder shows no progress

#### Collector

- [ ] Can be crafted
- [ ] Can be crafted with modded chicken
- [ ] Has localized name
- [ ] Textures look correct
- [ ] Pulls items from roost 4 blocks north and 4 blocks west
- [ ] Pulls items from roost 4 blocks south and 4 blocks east
- [ ] Pulls items from roost 2 blocks above
- [ ] Hoppers can pull items out
- [ ] Hoppers can put items in
- [ ] [GUI] Can shift+click item in and out

#### Chicken

- [ ] Has correct texture
- [ ] Has correct texture for modded
- [ ] Vanilla chicken spawns a vanilla chicken on right click
- [ ] Modded chicken spawns a modded chicken on right click
- [ ] Modded chicken spawns a modded chicken with the correct stats on right click
- [ ] Vanilla chicken has localized name
- [ ] Modded chickens have localized names
- [ ] [JEI] Has localized name in recipe display

#### Chicken Catcher

- [ ] Can be crafted
- [ ] Has localized name
- [ ] Has correct texture
- [ ] Can catch a vanilla chicken
- [ ] Can catch a modded chicken with correct stats

#### Chickens

- [ ] Has all chicken item textures
- [ ] Has all roost chicken textures

#### More Chickens

- [ ] Has all chicken item textures
- [ ] Has all roost chicken textures
